//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFCRUDUsuarios
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registrado
    {
        public long NroIdUsuario { get; set; }
        public string TipoIdUsuario { get; set; }
        public byte[] Foto { get; set; }
        public string DirCorreo { get; set; }
        public string Password { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
